# Generated by Django 5.1.4 on 2025-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_category_tag_alter_post_image_post_category_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
